### PR TITLE
feature/#3_i18n

### PR DESCRIPTION
**Pull request by yuu-eguci**
@Avalonalan As long as no comment is added, this PR doesn't require your review. Please take a look for review when I add comment!

## Related issue number

#3

### CODE REVIEW

**Comment by Avalonalan** [comment]
@yuu-eguci 
I'll review it but sometimes I am really occupied. Sorry

**Comment by Avalonalan** [comment]
@yuu-eguci 
I don't see any changed files here. Should I merge it ?

**Comment by yuu-eguci** [comment]
@Avalonalan Not yet!

As I wrote like below

> As long as no comment is added, this PR doesn't require your review. Please take a look for review when I add comment!

I will tell you at PR comment tree here when I need your review! Thank you.

**Comment by yuu-eguci** [comment]
@Avalonalan 
Hi! I succeeded to serve the project on local environment with each language, from each URLs such as /ja/ and /ro/ like below!
Please review!

pr

**Comment by yuu-eguci** [comment]
@Avalonalan Thanks for merge!

**Pull request merged**
